[providers.node]
version = "20"

[phases.install]
cmds = [
  "npm ci --include=dev",
  "npm install -g tsx"
]

[phases.build]
cmds = [
  "echo 'Using tsx runtime, skipping TypeScript build'"
]

[start]
cmd = "npm run start:sse:tsx"

[variables]
NODE_ENV = "production"
SHAPE_SSE_MODE = "true"