[providers.node]
version = "20"

[phases.install]
cmds = [
  "npm ci --include=dev",
  "npm install -g tsx"
]

[phases.build]
cmds = [
  "echo 'Skipping TypeScript build - using tsx runtime'"
]

[start]
cmd = "SHAPE_SSE_MODE=true tsx src/index.ts"