[build]
builder = "NIXPACKS"

[deploy]
startCommand = "SHAPE_SSE_MODE=true tsx src/index.ts"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10