import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'MPCM-Pro Demo App',
  description: 'Generated by MPCM-Pro multi-service orchestration',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
